"""add order phone

Revision ID: 28aa989aca94
Revises: 25a22866bd02
Create Date: 2016-12-25 23:14:26.516166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28aa989aca94'
down_revision = '25a22866bd02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('phone', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'phone')
    # ### end Alembic commands ###
