"""add order message

Revision ID: 45f53f5f6195
Revises: 99615e34b717
Create Date: 2016-12-27 22:24:26.214446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f53f5f6195'
down_revision = '99615e34b717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('message', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'message')
    # ### end Alembic commands ###
