"""add user id 

Revision ID: 4a15a824297a
Revises: 4a4cfb61fe74
Create Date: 2016-12-26 12:18:57.792375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a15a824297a'
down_revision = '4a4cfb61fe74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'user_id')
    # ### end Alembic commands ###
