"""change permissions to json

Revision ID: 4a4cfb61fe74
Revises: f78b1ad9d6d0
Create Date: 2016-12-26 11:18:46.688964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a4cfb61fe74'
down_revision = 'f78b1ad9d6d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permissions_json', sa.String(length=255), nullable=True))
    op.drop_column('roles', 'permissions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permissions', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('roles', 'permissions_json')
    # ### end Alembic commands ###
