"""add product code

Revision ID: 5fc463bb98b0
Revises: deaf4ea7995f
Create Date: 2016-12-23 11:01:12.341475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fc463bb98b0'
down_revision = 'deaf4ea7995f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('code', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'products', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'code')
    # ### end Alembic commands ###
