"""add operation records

Revision ID: 7a082b06b323
Revises: ba8e41de2235
Create Date: 2016-12-22 11:36:03.060666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a082b06b323'
down_revision = 'ba8e41de2235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=False),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=False),
    sa.Column('model_type', sa.String(length=32), nullable=False),
    sa.Column('model_type_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation_records')
    # ### end Alembic commands ###
