"""add operation state

Revision ID: 99615e34b717
Revises: 4a15a824297a
Create Date: 2016-12-27 12:17:04.424399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99615e34b717'
down_revision = '4a15a824297a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation_records', sa.Column('state', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operation_records', 'state')
    # ### end Alembic commands ###
