"""order item related to products

Revision ID: c8f845d11374
Revises: 4f74ecfc6540
Create Date: 2016-12-22 11:46:00.927075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8f845d11374'
down_revision = '4f74ecfc6540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=False),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=8, scale=2, asdecimal=False), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=8, scale=2, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('product')
    op.add_column('order_items', sa.Column('product_id', sa.Integer(), nullable=False))
    op.alter_column('order_items', 'order_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.alter_column('order_items', 'order_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('order_items', 'product_id')
    op.create_table('product',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=False),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('purchase_price', mysql.DECIMAL(precision=8, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('products')
    # ### end Alembic commands ###
