"""add state in orders

Revision ID: dab8150b55dc
Revises: c8f845d11374
Create Date: 2016-12-22 12:29:45.777881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dab8150b55dc'
down_revision = 'c8f845d11374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('state', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'state')
    # ### end Alembic commands ###
