"""add operation type

Revision ID: deaf4ea7995f
Revises: dab8150b55dc
Create Date: 2016-12-23 10:42:29.423183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deaf4ea7995f'
down_revision = 'dab8150b55dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation_records', sa.Column('operation_type', sa.String(length=32), nullable=True))
    op.add_column('operation_records', sa.Column('operation_type_value', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operation_records', 'operation_type_value')
    op.drop_column('operation_records', 'operation_type')
    # ### end Alembic commands ###
