"""add Column orders

Revision ID: f485de3ead29
Revises: 5be1daa7399c
Create Date: 2016-12-22 11:37:27.525705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f485de3ead29'
down_revision = '5be1daa7399c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('cost', sa.Numeric(precision=8, scale=2, asdecimal=False), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'cost')
    # ### end Alembic commands ###
