"""change permissions

Revision ID: f78b1ad9d6d0
Revises: 28aa989aca94
Create Date: 2016-12-26 11:09:07.045624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f78b1ad9d6d0'
down_revision = '28aa989aca94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
